name: Build on push

on:
  push:
    branches:
      - '**'

jobs:
  api:
    -
      uses: ./.github/world-api.yml
      secrets:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
